name = "mizuki-blog"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-12-16"

[build]
cwd = "."
command = "pnpm run build"
watch_paths = ["src/**/*.ts", "src/**/*.astro"]

[build.upload]
main = "./dist"

[env.production]
name = "mizuki-blog"
